# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Taxikick
tagline:             'Report abusive taxi drivers in the Philippines'
description:         'Taxikick is a simple web app that helps Filipino commuters to report abusive taxi drivers.'
url:                 http://taxikick.com
baseurl:             ''

# About/contact
author:
  name:              Taxikick
  url:               https://twitter.com/taxikick
  email:             hello@taxikick.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"